In [1]:
import pandas as pd
import statsmodels.api as sm

In [2]:
consumption = pd.read_csv('Tables/consumption adjusted.csv', index_col=0)
consumption

,Product,Week Ending,Week,Consumption,SKU,EASTER,MEMORIAL,4th OF JULY,LABOR DAY,HALLOWEEN,...,DIGITAL,SPONSORSHIP,PRINT,RADIO,VOD,BILLBOARD,INFLUENCER,BASEBALL,Avg Price,ACV
0,04 Total King's Hawaiian,2016/1/3,1,2515233.293,Total US,0,0,0,0,0,...,0.00,0.0,0.00,0.0,0.00000,0.0,0.0,0.0,3.384393,86.864850
1,04 Total King's Hawaiian,2016/1/10,2,1770268.406,Total US,0,0,0,0,0,...,0.00,0.0,0.00,0.0,0.00000,0.0,0.0,0.0,3.212311,86.876704
2,04 Total King's Hawaiian,2016/1/17,3,1694926.855,Total US,0,0,0,0,0,...,0.00,0.0,0.00,0.0,0.00000,0.0,0.0,0.0,3.196794,86.715495
3,04 Total King's Hawaiian,2016/1/24,4,1728764.425,Total US,0,0,0,0,0,...,0.00,0.0,0.00,0.0,0.00000,0.0,0.0,0.0,3.171266,86.692429
4,04 Total King's Hawaiian,2016/1/31,5,1578573.962,Total US,0,0,0,0,0,...,0.00,0.0,0.00,0.0,29677.41935,0.0,0.0,0.0,3.141820,86.148075
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241,04 Total King's Hawaiian,8/16/2020,242,2474038.330,Total US,0,0,0,0,0,...,41876.00,0.0,89795.25,0.0,0.00000,0.0,116000.0,0.0,3.860006,89.019559
242,04 Total King's Hawaiian,8/23/2020,243,2481435.718,Total US,0,0,0,0,0,...,260257.16,0.0,89795.25,0.0,0.00000,0.0,0.0,0.0,3.794589,88.917161
243,04 Total King's Hawaiian,8/30/2020,244,2482365.267,Total US,0,0,0,0,0,...,180830.49,0.0,89795.25,0.0,0.00000,0.0,0.0,0.0,3.844261,88.685702
244,04 Total King's Hawaiian,9/6/2020,245,3042470.983,Total US,0,0,0,1,0,...,170830.49,56250.0,0.00,0.0,0.00000,0.0,0.0,0.0,3.913313,88.829812
245,04 Total King's Hawaiian,9/13/2020,246,2666847.075,Total US,0,0,0,0,0,...,152442.49,56250.0,0.00,0.0,0.00000,0.0,116000.0,0.0,3.858334,88.759292

In [3]:
y = consumption.Consumption

In [4]:
y

0      2515233.293
1      1770268.406
2      1694926.855
3      1728764.425
4      1578573.962
          ...
241    2474038.330
242    2481435.718
243    2482365.267
244    3042470.983
245    2666847.075
Name: Consumption, Length: 246, dtype: float64

In [5]:
X = consumption.iloc[:,5:-2]

In [6]:
X

,EASTER,MEMORIAL,4th OF JULY,LABOR DAY,HALLOWEEN,THANKSGIVING&HOLIDAY,TV,DIGITAL,SPONSORSHIP,PRINT,RADIO,VOD,BILLBOARD,INFLUENCER,BASEBALL
0,0,0,0,0,0,0,0.0000,0.00,0.0,0.00,0.0,0.00000,0.0,0.0,0.0
1,0,0,0,0,0,0,0.0000,0.00,0.0,0.00,0.0,0.00000,0.0,0.0,0.0
2,0,0,0,0,0,0,0.0000,0.00,0.0,0.00,0.0,0.00000,0.0,0.0,0.0
3,0,0,0,0,0,0,0.0000,0.00,0.0,0.00,0.0,0.00000,0.0,0.0,0.0
4,0,0,0,0,0,0,362991.5103,0.00,0.0,0.00,0.0,29677.41935,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241,0,0,0,0,0,0,0.0000,41876.00,0.0,89795.25,0.0,0.00000,0.0,116000.0,0.0
242,0,0,0,0,0,0,550353.1385,260257.16,0.0,89795.25,0.0,0.00000,0.0,0.0,0.0
243,0,0,0,0,0,0,688421.1765,180830.49,0.0,89795.25,0.0,0.00000,0.0,0.0,0.0
244,0,0,0,1,0,0,701462.8765,170830.49,56250.0,0.00,0.0,0.00000,0.0,0.0,0.0
245,0,0,0,0,0,0,703451.9765,152442.49,56250.0,0.00,0.0,0.00000,0.0,116000.0,0.0

In [9]:
display = pd.read_csv('Tables/Display.csv')

In [10]:
display = display.iloc[:,4:].reset_index(drop =True)

In [11]:
display

,Large Hutch,Large Header Only,Meat Bunker,4-way/WOW,Small Hutch,Grill
0,0,0,0,0,0,0
1,0,0,0,0,0,0
2,0,0,0,0,0,0
3,0,0,0,0,0,0
4,0,0,0,0,0,0
...,...,...,...,...,...,...
241,0,0,0,0,0,0
242,3130,880,0,3878,0,0
243,3130,880,0,3878,0,0
244,3130,880,0,3878,0,0
245,3130,880,0,3878,0,0

In [12]:
X = pd.concat([X, display], axis=1)
X = sm.add_constant(X)

In [13]:
X

,const,EASTER,MEMORIAL,4th OF JULY,LABOR DAY,HALLOWEEN,THANKSGIVING&HOLIDAY,TV,DIGITAL,SPONSORSHIP,...,VOD,BILLBOARD,INFLUENCER,BASEBALL,Large Hutch,Large Header Only,Meat Bunker,4-way/WOW,Small Hutch,Grill
0,1.0,0,0,0,0,0,0,0.0000,0.00,0.0,...,0.00000,0.0,0.0,0.0,0,0,0,0,0,0
1,1.0,0,0,0,0,0,0,0.0000,0.00,0.0,...,0.00000,0.0,0.0,0.0,0,0,0,0,0,0
2,1.0,0,0,0,0,0,0,0.0000,0.00,0.0,...,0.00000,0.0,0.0,0.0,0,0,0,0,0,0
3,1.0,0,0,0,0,0,0,0.0000,0.00,0.0,...,0.00000,0.0,0.0,0.0,0,0,0,0,0,0
4,1.0,0,0,0,0,0,0,362991.5103,0.00,0.0,...,29677.41935,0.0,0.0,0.0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241,1.0,0,0,0,0,0,0,0.0000,41876.00,0.0,...,0.00000,0.0,116000.0,0.0,0,0,0,0,0,0
242,1.0,0,0,0,0,0,0,550353.1385,260257.16,0.0,...,0.00000,0.0,0.0,0.0,3130,880,0,3878,0,0
243,1.0,0,0,0,0,0,0,688421.1765,180830.49,0.0,...,0.00000,0.0,0.0,0.0,3130,880,0,3878,0,0
244,1.0,0,0,0,1,0,0,701462.8765,170830.49,56250.0,...,0.00000,0.0,0.0,0.0,3130,880,0,3878,0,0
245,1.0,0,0,0,0,0,0,703451.9765,152442.49,56250.0,...,0.00000,0.0,116000.0,0.0,3130,880,0,3878,0,0

In [14]:
model = sm.OLS(y, X)
result = model.fit()
print(result.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:            Consumption   R-squared:                       0.819
Model:                            OLS   Adj. R-squared:                  0.802
Method:                 Least Squares   F-statistic:                     48.13
Date:                Thu, 03 Dec 2020   Prob (F-statistic):           5.74e-71
Time:                        18:18:58   Log-Likelihood:                -3587.5
No. Observations:                 246   AIC:                             7219.
Df Residuals:                     224   BIC:                             7296.
Df Model:                          21
Covariance Type:            nonrobust
========================================================================================
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
const                 2.018e+06   7.01e+04     28.784      0.000    1.88e+06    2.16e+06
EASTER                2.046e+06   2.56e+05      7.983      0.000    1.54e+06    2.55e+06
MEMORIAL              2.509e+05   2.67e+05      0.941      0.348   -2.75e+05    7.76e+05
4th OF JULY           6.217e+05   2.63e+05      2.359      0.019    1.02e+05    1.14e+06
LABOR DAY             4.066e+05   2.57e+05      1.584      0.115   -9.94e+04    9.13e+05
HALLOWEEN             5.926e+04   2.94e+05      0.202      0.840    -5.2e+05    6.39e+05
THANKSGIVING&HOLIDAY  4.223e+06   1.57e+05     26.828      0.000    3.91e+06    4.53e+06
TV                       0.0244      0.126      0.194      0.846      -0.223       0.272
DIGITAL                 -1.1781      0.835     -1.411      0.160      -2.824       0.467
SPONSORSHIP             -0.8922      0.610     -1.463      0.145      -2.094       0.309
PRINT                    1.7028      2.013      0.846      0.398      -2.263       5.669
RADIO                    0.2472      1.960      0.126      0.900      -3.614       4.109
VOD                     -0.4821      2.416     -0.200      0.842      -5.243       4.279
BILLBOARD                3.2407      1.198      2.704      0.007       0.879       5.602
INFLUENCER               4.5763      2.753      1.663      0.098      -0.848      10.001
BASEBALL                 0.7698      2.376      0.324      0.746      -3.913       5.453
Large Hutch             23.5557     13.049      1.805      0.072      -2.159      49.270
Large Header Only      339.7692    105.072      3.234      0.001     132.713     546.825
Meat Bunker              3.4236     37.719      0.091      0.928     -70.907      77.754
4-way/WOW               -4.9511     56.256     -0.088      0.930    -115.811     105.908
Small Hutch            -65.8899    218.294     -0.302      0.763    -496.063     364.283
Grill                   32.0402     33.820      0.947      0.344     -34.606      98.686
==============================================================================
Omnibus:                       77.601   Durbin-Watson:                   2.378
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1412.256
Skew:                           0.691   Prob(JB):                    2.15e-307
Kurtosis:                      14.656   Cond. No.                     3.67e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.67e+06. This might indicate that there are
strong multicollinearity or other numerical problems.